name: build project

on: [ push ]

jobs:
  build:
    runs-on: self-hosted

    steps:
        - name: build with msbuild
          run: |
            cd build
            dotnet msbuild _build.csproj
