name: build project

on: [ push ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: build with msbuild
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.3.1
      - run: msbuild build/_build.csproj
