name: Run commands on different operating systems
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build-project
    runs-on: self-hosted
    steps:
      - run: dotnet msbuild build/_build.csproj
