name: build project

on: [ push ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v3
      - name: Install msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: build with msbuild
        run: msbuild build/_build.csproj
