name: Start build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: build project
    - run: dotnet /build/_build.csproj
