name: build project

on: [ push ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install msbuild
        uses: actions/checkout@v2
      - name: build with msbuild
        run: msbuild build/_build.csproj
